services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photogallery_web
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - db
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET:-thisisasecret222changemeinproduction}
      DATABASE_URL: postgres://postgres:postgres@db:5432/photogallery_web
      # JWT Configuration
      JWT_SECRET_KEY: '%kernel.project_dir%/config/jwt/private.pem'
      JWT_PUBLIC_KEY: '%kernel.project_dir%/config/jwt/public.pem'
      JWT_PASSPHRASE: '${JWT_PASSPHRASE}'
      PHOENIX_API_URL: 'http://host.docker.internal:4000/api/photos'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db-data:
