version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photogallery_web
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - db
    environment:
      APP_ENV: dev
      APP_SECRET: ${APP_SECRET:-thisisasecret222changemeinproduction}
      DATABASE_URL: postgres://postgres:postgres@db:5432/photogallery_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db-data: