
version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: photogallery_api
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - db
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/photogallery_api
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-thisisasecret111changemeinproduction}
      PHX_HOST: 0.0.0.0
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - .:/app

volumes:
  db-data: