login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: [GET, POST]

logout:
    path: /logout
    controller: App\Controller\AuthController::logout

home:
    path: /
    controller: App\Controller\HomeController::index

photo_like:
    path: /photo/{id}/like
    controller: App\Controller\PhotoController::like
    methods: [POST]

profile:
    path: /profile
    controller: App\Controller\ProfileController::profile
    methods: [GET, POST]

profile_import:
    path: /profile/import
    controller: App\Controller\ProfileController::importPhotos
    methods: [POST]
