services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

parameters:
    env(PHOENIX_API_URL): 'http://localhost:4000/api/photos'
    app.phoenix_api_url: '%env(PHOENIX_API_URL)%'
